#' @title Import data files from the old generation of Oregon RFID readers
#' @description Function to import files recorded by the first generations of Oregon RFID readers. 
#' @param file txt file generated by an Oregor RFID reader.
#' @param delim the field separator character. Values on each line of the file are separated by this character and it must be either tab, comma or semi-colon.
#' @details A data frame is created in the user environment from a import of a Oregor RFID reader file.
#'   
#' the field separator character must be either tab, comma or semi-colon otherwise the function cannot organize properly the variables, generating error messages, without import the file.
#' 
#' The Tag number (TAG) is required for further estatistical analysis. Consider in upload the data from the ORFID reader with variable selected in the Reader field names.
#' @return Returns a tibble object.
#' @author Hugo Marques <biohmarques@@gmail.com>
#' @importFrom magrittr %>%
#' @export
#' @examples
#' \dontrun{
#' Teste
#' }

###############################################################################


import_old_readers <- function (file, delim, site_code){
    
    if (!(delim %in% c("\t", ",", ";"))) {
        stop("The column separator must be '\t', ',' or ';'")
    }
    
    if(is.na(grep("Gap", readLines(file))[1]) == T){
        stop("The header is missing in the UP output. Please review the text file.")
    }
    
    if(length(grep("Gap", readLines(file))) > 1){
        warning("More than one UP in the same file. Only the first will be imported.")
    }
    
    raw_data <- readr::read_delim(file, 
                                  delim = delim, 
                                  skip = grep("Gap", readLines(file)[1] -1))
    
    colnames(raw_data) <- c("DTY", "Date", "Time", "DUR", "Type", "TAG", "NCD", "EMP")
    
    site_name <- grep("^Reader*", readLines(file), value = TRUE)
    
    site_code <- stringr::str_extract(site_name, '\\w*$')[1]
    
    raw_data <- raw_data %>% 
        tidyr::unite("ARR", Date:Time, sep = " ", remove = FALSE) %>% 
        tidyr::separate(Type, sep = 1, into = c("TCH", "TTY")) %>% 
        dplyr::mutate(SCD = as.factor(site_code)) %>%
        dplyr::select(-c(Date, Time)) %>% 
        dplyr::filter(DTY == "D")
    
    
    if (("ARR" %in% names(raw_data))) {
        raw_data <- raw_data %>% 
            dplyr::mutate(ARR = readr::parse_datetime(ARR, "%Y-%m-%d %H:%M:%OS"))
    }
    if (("DUR" %in% names(raw_data))) {
        raw_data <- raw_data %>% 
            dplyr::mutate(DUR = readr::parse_time(DUR, "%H:%M:%OS"))
    }
    if (("TTY" %in% names(raw_data))) {
        raw_data <- raw_data %>% 
            dplyr::mutate(TTY = as.factor(TTY))
    }
    if (("EMP" %in% names(raw_data))) {
        raw_data <- raw_data %>% 
            dplyr::mutate(EMP = as.double(EMP))
    }
    if (!("TAG" %in% names(raw_data))) {
        warning("The Tag number (TAG) is required for further analysis. Consider upload the data from the ORFID reader again making sure the TAG is selected in the field name")
        Sys.sleep(3)
    }
    
    return(dplyr::glimpse(raw_data))
    
}

