#' @title Import event records from the new generation of Oregon RFID readers
#' @description Function to import event records from files recorded by the new generation of Oregon RFID readers. 
#' @param file txt file generated by an Oregor RFID reader.
#' @param delim the field separator character. Values on each line of the file are separated by this character and it must be either tab, comma or semi-colon.
#' @details A data frame is created in the user environment from a import of a Oregor RFID reader file.
#'   
#' the field separator character must be either tab, comma or semi-colon otherwise the function cannot organize properly the variables, generating error messages, without import the file.
#' 
#' @return Returns a tibble object.
#' @author Hugo Marques <biohmarques@@gmail.com>
#' @importFrom magrittr %>%
#' @export
#' @examples
#' \dontrun{
#' 
#' ##  Importing the event records from the ORFID reader data to the user working directory
#' data_BRA <- import_ORFID_events("~/Desktop/SCD_BRA.txt")
#' 
#' }

###############################################################################

import_ORFID_events <- function(file, delim){
    
    if (!(delim %in% c("\t", ",", ";"))) {
        stop("The column separator must be '\t', ',' or ';'")
    }
    
    raw_data <- readr::read_delim(file, delim = delim, skip = grep("* records ---------$", readLines(file)))
    
    if(("SCD" %in% names(raw_data))){
        
        site_code <- raw_data %>%
            dplyr::mutate(SCD = as.factor(SCD)) %>% 
            dplyr::distinct(SCD)
        
        raw_data <- raw_data %>%
            dplyr::filter(DTY == "E") %>%
            dplyr::mutate(SCD = as.factor(site_code)) %>% 
            dplyr::mutate(message = DUR) %>%
            dplyr::mutate(TRF = as.factor(TRF)) %>%
            dplyr::select(DTY, SCD, ARR, TRF, message)
        
    } else {
        
        raw_data <- raw_data %>%
            dplyr::filter(DTY == "E") %>%
            dplyr::mutate(SCD = as.factor(site_code)) %>% 
            dplyr::mutate(message = DUR) %>%
            dplyr::mutate(TRF = as.factor(TRF)) %>%
            dplyr::select(DTY, SCD, ARR, TRF, message)
        
    }
    
    return(dplyr::glimpse(raw_data))
    
}

###############################################################################

###############################################################################