#' @title Import event records from the new generation of Oregon RFID readers
#' @description Function to import event records from files generated by the new generation of Oregon RFID readers. 
#' @param file .txt file generated by an Oregon RFID reader.
#' @param delim field separator character, which must be tab (\t), comma, or semi-colon.
#' @details A data frame is created in the user environment containing only event records (no detection data) from an Oregon RFID reader file.
#'   
#' The field separator character must be either tab, comma or semi-colon; space separators are not permitted.
#' 
#' @return Returns a tibble object.
#' @author Hugo Marques <biohmarques@@gmail.com>
#' @importFrom magrittr %>%
#' @export
#' @examples
#' \dontrun{
#' 
#' ##  Importing the event records from the ORFID reader data to the user working directory
#' data_BRA <- import_ORFID_events("~/Desktop/SCD_BRA.txt")
#' 
#' }

import_ORFID_events <- function(file, delim){
    
    if (!(delim %in% c("\t", ",", ";"))) {
        stop("The column separator must be '\t', ',' or ';'")
    }
    
    raw_data <- readr::read_delim(file, delim = delim, skip = grep("* records ---------$", readLines(file)))
    
    if(("SCD" %in% names(raw_data))) {
        
        site_code <- raw_data %>% 
            dplyr::distinct(SCD) %>% 
            dplyr::filter(!is.na(SCD))
        
        raw_data2 <- raw_data %>%
            dplyr::filter(DTY == "E") %>%
            dplyr::mutate(SCD = site_code) %>% 
            dplyr::mutate(message = DUR) %>%
            dplyr::mutate(TRF = as.factor(TRF)) %>%
            dplyr::select(DTY, SCD, ARR, TRF, message)
        
    }
    
    if((!"SCD" %in% names(raw_data))) {
        
        raw_data2 <- raw_data %>%
            dplyr::filter(DTY == "E") %>%
            dplyr::mutate(SCD = "NA") %>% 
            dplyr::mutate(message = DUR) %>%
            dplyr::mutate(TRF = as.factor(TRF)) %>%
            dplyr::select(DTY, SCD, ARR, TRF, message)
        
        Sys.sleep(3)
        warning("Site code (SCD) is required for further analysis and should be included as a field name.")
        
    }
    
    return(dplyr::glimpse(raw_data2))
    
}
