#' @title Import data files from the new generation of Oregon RFID readers
#'
#' @description Function to import files recorded by the new generation of Oregon RFID readers. 
#' @param file txt file generated by an Oregor RFID reader.
#' @param delim the field separator character. Values on each line of the file are separated by this character.
#' @details Data frame is created in the user environment.
#' @examples
#' #save data frame to a working directory
#' \dontrun{} import_ORFID("~/Desktop/SCD_BRA.txt")
#' @export

###############################################################################

import_ORFID <- function(file, delim){
    
    if (!(delim %in% c("\t", ","))) {
        stop("The column separator must be either tab '\' or ','")
    }
    
    raw_data <- read_delim(file, delim = "\t", skip = grep("--------- Upload", readLines(file)))
    
    PIT_data <<- raw_data %>%
        filter(DTY == "S" | DTY == "I") %>%
        mutate(DUR=parse_time(DUR, '%H:%M:%OS')) %>%
        mutate(TTY=as.factor(TTY)) %>%
        mutate(SCD=as.factor(SCD))
    
    return(glimpse(PIT_data))
    
}

###############################################################################