#' @title Import data files from the old generation of Oregon RFID readers
#' @description Function to import files recorded by the first generations of Oregon RFID readers. 
#' @param file txt file generated by an Oregor RFID reader.
#' @param delim the field separator character. Values on each line of the file are separated by this character and it must be either tab, comma or semi-colon.
#' @details A data frame is created in the user environment from a import of a Oregor RFID reader file.
#'   
#' the field separator character must be either tab, comma or semi-colon otherwise the function cannot organize properly the variables, generating error messages, without import the file.
#' 
#' The Tag number (TAG) is required for further estatistical analysis. Consider in upload the data from the ORFID reader with variable selected in the Reader field names.
#' @return Returns a tibble object.
#' @author Hugo Marques <biohmarques@@gmail.com>
#' @importFrom magrittr %>%
#' @export
#' @examples
#' \dontrun{
#' 
#' 
#' }

###############################################################################

import_ORFID <- function(file, delim){
    
    if (!(delim %in% c("\t", ",", ";"))) {
        stop("The column separator must be '\t', ',' or ';'")
    }
    
    raw_data <- readr::read_delim(file, delim = delim, skip = grep("* ---------$", readLines(file)))
    
    raw_data <- raw_data %>%
        dplyr::unite("ARR", Date:Time, sep = " ", remove = FALSE) %>%
        rename(DTY = Type) %>%
        rename(DUR = Duration) %>%
        rename(TTY = Type_1) %>%
        rename(TAG = 'Tag ID') %>%
        rename(NCD = Count) %>%
        rename(EMP = Gap)
    
    raw_data <- raw_data %>%
        dplyr::filter(DTY == "S" | DTY == "I")

    if(("DUR" %in% names(raw_data))){
        raw_data <- raw_data %>%
            dplyr::mutate(DUR = readr::parse_time(DUR, '%H:%M:%OS'))
    }
    
    if(("SCD" %in% names(raw_data))){
        raw_data <- raw_data %>%
            dplyr::mutate(SCD = as.factor(SCD))
    }
    
    if(("TTY" %in% names(raw_data))){
        raw_data <- raw_data %>%
            dplyr::mutate(TTY = as.factor(TTY))
    }
    
    if(!("TAG" %in% names(raw_data))){
        Sys.sleep(3)
        warning("The Tag number (TAG) is required for further analysis. Consider upload the data from the ORFID reader again making sure the TAG is selected in the field name")
    }
    
    return(dplyr::glimpse(raw_data))
    
}

###############################################################################

###############################################################################