#' @title Import data files from the new generation of Oregon RFID readers
#'
#' @description Function to import files recorded by the new generation of Oregon RFID readers. 
#' @param file txt file generated by an Oregor RFID reader.
#' @param delim the field separator character. Values on each line of the file are separated by this character.
#' @param skip integer: the number of lines of the data file to skip before beginning to read data.
#' @details Data frame is saved in the user-specified working directory.
#' @examples
#' #save data frame to a working directory
#' \dontrun{} ORFID_import("~/Desktop/SCD_BRA.txt")
#' @export


ORFID_import <- function(file, delim = "\t", skip = NULL){
    #Import the 
    if (!(delim %in% c("\t", ","))) {
        stop("The column separator must be either tab '\' or ','")
    }
    
    if (is.null(skip)) {
        stop("The number of lines to skip before reading data is mandatory. Count the number of the lines before the data header in the txt file to be imported and assigning this value for the argument 'skip'.")
    }
        
    raw_data <- read_delim(file, delim = delim, skip = skip)
    
    PIT_data <<- raw_data %>%
        filter(DTY == "S" | DTY == "I") %>%
        mutate(DUR=parse_time(DUR, '%H:%M:%OS')) %>%
        mutate(TTY=as.factor(TTY)) %>%
        mutate(SCD=as.factor(SCD))
    
    return(glimpse(PIT_data))
    
}

###############################################################################